name: development deploy

on:
  push:
    branches: [ development ]


jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: pull the changes
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.KEY }}
          script: |
            cd /var/www/b2sw-dev/
            git pull origin development
            composer install
            php artisan migrate:fresh --seed
            php artisan optimize






